Repository SharePoint/sp-dev-docs, pull requests merged in 2020-06, with the labels that each got.

#5822 Update working-with-lists-and-list-items-with-rest.md
  docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md
Labels: pr:ready-to-merge

#5831 refresh tenant properties readability
  docs/spfx/tenant-properties.md
  includes/snippets/open-source/pnp-o365cli.md
  includes/snippets/open-source/pnp-powershell.md
Labels: pr:ready-to-merge

#5836 Change the link in the 'see also' section
  docs/general-development/site-collection-app-catalog.md
Labels: pr:in-review

#5841 refresh ALM API doc
  docs/apis/alm-api-for-spfx-add-ins.md
Labels: pr:ready-to-merge

#5854 Add known issue implicit auth fail no AAD roles
  docs/spfx/use-msgraph.md
Labels: pr:ready-to-merge

#5832 Adding extra level of detail to avoid ambiguity
  docs/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online.md
Labels: pr:ready-to-merge

#5842 Updated site-footer.md
  docs/features/site-footer.md
  docs/images/Footer-CTL-Configutation.png
  docs/images/footer-change-the-look.png
Labels: pr:ready-to-merge

#5857 Updating CreateSiteDesign Parameters
  docs/declarative-customization/site-design-rest-api.md
Labels: pr:ready-to-merge

#5818 update toc.yml
  docs/toc.yml
Labels: pr:ready-to-merge

#5873 update toc.yml
  docs/toc.yml
  hierarchy-ABCD.png
  hierarchy-perms.png
Labels: pr:ready-to-merge

#5874 update migration api overview
  docs/apis/migration-api-overview.md
Labels: pr:ready-to-merge

#5875 Mentioned cloud platform applicability
  docs/features/embed-pages-to-teams.md
Labels: pr:ready-to-merge

#5878 Fixup build error reports
  docs/apis/migration-perm-guidance.md
  docs/images/hierarchy-ABCD.png
  docs/images/hierarchy-perms.png
  hierarchy-ABCD.png
  hierarchy-perms.png
Labels: pr:in-review

#5876 Update embed-pages-to-teams.md
  docs/features/embed-pages-to-teams.md
Labels: pr:do-not-merge

#5837 Docupdate opensource pnp
  docs/apis/alm-api-for-spfx-add-ins.md
  docs/apis/site-creation-rest.md
  docs/declarative-customization/site-design-o365cli.md
  docs/declarative-customization/site-design-pnp-provisioning.md
  docs/declarative-customization/site-design-pnppowershell.md
  docs/declarative-customization/site-design-powershell.md
  docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md
  docs/features/hub-site/create-hub-site-with-powershell.md
  docs/features/hub-site/hub-site-o365cli.md
  docs/features/site-footer.md
  docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md
  docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md
  docs/general-development/site-collection-app-catalog.md
  docs/solution-guidance/Bulk-user-profile-update-api-for-sharepoint-online.md
  docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md
  docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-Feature-Receivers.md
  docs/solution-guidance/modern-experience-customizations-customize-lists-and-libraries.md
  docs/solution-guidance/modern-experience-customizations-customize-pages.md
  docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
  docs/solution-guidance/modern-experience-customizations.md
  docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md
  docs/solution-guidance/pnp-provisioning-framework.md
  docs/solution-guidance/pnp-provisioning-schema.md
  docs/solution-guidance/pnp-provisioning-tenant-templates.md
  docs/solution-guidance/pnp-remote-provisioning.md
  docs/solution-guidance/portal-performance.md
  docs/solution-guidance/provisioning-console-application-sample.md
  docs/solution-guidance/security-apponly-azureacs.md
  docs/solution-guidance/security-apponly-azuread.md
  docs/solution-guidance/security-permissivesetting.md
  docs/solution-guidance/security-webapppolicies.md
  docs/solution-guidance/the-pnp-office-open-xml-file-format.md
  docs/spfx/connect-to-sharepoint.md
  docs/spfx/extensions/get-started/building-simple-field-customizer.md
  docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
  docs/spfx/use-aadhttpclient.md
  docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
  docs/spfx/web-parts/single-part-app-pages.md
  docs/transform/modernize-blogs.md
  docs/transform/modernize-branding.md
  docs/transform/modernize-userinterface-lists-and-libraries-optout.md
  docs/transform/modernize-userinterface-lists-and-libraries.md
  docs/transform/modernize-userinterface-site-pages-dotnet.md
  docs/transform/modernize-userinterface-site-pages-powershell.md
  docs/transform/modernize-userinterface-site-pages-usermapping.md
  includes/snippets/open-source/pnp-js.md
  includes/snippets/open-source/pnp-o365cli.md
  includes/snippets/open-source/pnp-powershell.md
  includes/snippets/open-source/pnp-provisioning-engine.md
  includes/snippets/open-source/pnp-sites-core.md
Labels: pr:ready-to-merge

#5887 #5886 fix some auth code flow samples
  docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md
Labels: pr:ready-to-merge

#5885 Adds the 'Build for Teams' section
  docs/images/build-for-teams/build-for-teams-add-personal-app.png
  docs/images/build-for-teams/build-for-teams-application-personal-folder.png
  docs/images/build-for-teams/build-for-teams-channel-add-tab.png
  docs/images/build-for-teams/build-for-teams-manifest-settings-webpart.png
  docs/images/build-for-teams/build-for-teams-manifest-teamsmanifest.png
  docs/images/build-for-teams/build-for-teams-manifest-teamspersonalapp.png
  docs/images/build-for-teams/build-for-teams-manifest-teamstab.png
  docs/images/build-for-teams/build-for-teams-personal-app.png
  docs/images/build-for-teams/build-for-teams-teams-manifest-personalapp-multipletabs.png
  docs/spfx/build-for-teams-configure-in-teams.md
  docs/spfx/build-for-teams-considerations.md
  docs/spfx/build-for-teams-expose-webparts-teams.md
  docs/spfx/build-for-teams-overview.md
  docs/toc.yml
Labels: pr:ready-to-merge

#5851 Adds SharePoint marketplace guidance
  docs/spfx/publish-to-marketplace.md
  docs/spfx/toolchain/sharepoint-framework-toolchain.md
Labels: pr:ready-to-merge

#5849 Add tutorial article on how to customize a form for a SharePoint list
  docs/business-apps/power-apps/get-started/create-your-first-custom-form.md
  docs/images/gs01-attachments-conditional-visibility.png
  docs/images/gs01-attachments-property-visible.png
  docs/images/gs01-create-a-custom-form-command-bar.png
  docs/images/gs01-image-control-selected.png
  docs/images/gs01-power-apps-studio-add-image.png
  docs/images/gs01-power-apps-studio-custom-form.png
  docs/images/gs01-publish-power-apps.png
  docs/images/gs01-save-power-apps.png
  docs/images/gs01-set-image-border-radius.png
  docs/images/gs01-set-image-height.png
  docs/images/gs01-set-image-picture.png
  docs/images/gs01-set-image-width.png
  docs/images/gs01-title-data-card-view-only.png
  docs/images/gs01-title-property-display-mode.png
  docs/images/gs01-unlock-attachments-data-card.png
  docs/images/gs01-unlock-title-data-card.png
Labels: pr:do-not-merge

#5909 Renamed API samples to proper SharePoint casing.
  docs/declarative-customization/customize-default-site-design.md
  docs/declarative-customization/site-design-overview.md
  docs/declarative-customization/site-design-rest-api.md
Labels: pr:in-review

#5910 update migration-isv-guidance.md
  docs/apis/migration-isv-guidance.md
Labels: pr:ready-to-merge

#5922 Fix-up markdown references to NPM packages
  docs/spfx/extensions/get-started/build-a-hello-world-extension.md
  docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
  docs/spfx/extensions/get-started/using-page-placeholder-with-extensions.md
  docs/spfx/office-addins-create.md
  docs/spfx/web-parts/basics/integrate-with-property-pane.md
  docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
  docs/spfx/web-parts/get-started/use-fabric-react-components.md
Labels: pr:in-review

#5927 Update markdown fenced code language errors
  docs/apis/alm-api-for-spfx-add-ins.md
  docs/apis/export-amr-api.md
  docs/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using.md
  docs/general-development/site-collection-app-catalog.md
  docs/general-development/social-feed-rest-api-reference-for-sharepoint.md
  docs/solution-guidance/Localize-UI-elements-sample-app-for-SharePoint.md
  docs/solution-guidance/create-ux-controls-by-using-sharepoint-provider-hosted-add-ins.md
  docs/solution-guidance/customize-the-ux-by-using-sharepoint-provider-hosted-add-ins.md
  docs/solution-guidance/implement-a-sharepoint-site-classification-solution.md
  docs/solution-guidance/improve-performance-in-sharepoint-provider-hosted-add-ins.md
  docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
  docs/sp-add-ins/access-sharepoint-data-from-add-ins-using-the-cross-domain-library.md
  docs/sp-add-ins/complete-basic-operations-using-javascript-library-code-in-sharepoint.md
  docs/sp-add-ins/complete-basic-operations-using-sharepoint-rest-endpoints.md
  docs/sp-add-ins/create-a-custom-proxy-page-for-the-cross-domain-library-in-sharepoint.md
  docs/sp-add-ins/customize-a-list-view-in-sharepoint-add-ins-using-client-side-rendering.md
  docs/sp-add-ins/highlight-content-and-enhance-the-functionality-of-sharepoint-hosted-sharepoint.md
  docs/sp-add-ins/localize-sharepoint-add-ins.md
  docs/sp-add-ins/query-a-remote-service-using-the-web-proxy-in-sharepoint.md
  docs/sp-add-ins/set-custom-permissions-on-a-list-by-using-the-rest-interface.md
  docs/sp-add-ins/upload-a-file-by-using-the-rest-api-and-jquery.md
  docs/sp-add-ins/use-the-client-side-people-picker-control-in-sharepoint-hosted-sharepoint-add-in.md
  docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md
  docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md
  docs/sp-add-ins/use-the-sharepoint-javascript-apis-to-work-with-sharepoint-data.md
  docs/sp-add-ins/working-with-folders-and-files-with-rest.md
  docs/spfx/connect-to-anonymous-apis.md
  docs/spfx/connect-to-sharepoint.md
  docs/spfx/css-recommendations.md
  docs/spfx/debug-modern-pages.md
  docs/spfx/dynamic-data.md
  docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md
  docs/spfx/office-ui-fabric-integration.md
  docs/spfx/subscribe-to-list-notifications.md
  docs/spfx/tenant-properties.md
  docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
  docs/spfx/toolchain/integrate-gulp-tasks-in-build-pipeline.md
  docs/spfx/toolchain/optimize-builds-for-production.md
  docs/spfx/toolchain/provision-sharepoint-assets.md
  docs/spfx/use-aad-tutorial.md
  docs/spfx/use-aadhttpclient-enterpriseapi-multitenant.md
  docs/spfx/use-aadhttpclient-enterpriseapi.md
  docs/spfx/use-developer-dashboard.md
  docs/spfx/web-parts/basics/working-with-requestdigest.md
  docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md
  docs/spfx/web-parts/get-started/office-addins-tutorial.md
  docs/spfx/web-parts/guidance/build-client-side-web-parts-with-angular-1-x.md
  docs/spfx/web-parts/guidance/connect-to-api-secured-with-aad.md
  docs/spfx/web-parts/guidance/localize-web-parts.md
  docs/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework.md
  docs/spfx/web-parts/guidance/migrate-jquery-datatables-script-to-spfx.md
  docs/spfx/web-parts/guidance/migrate-jquery-fullcalendar-script-to-spfx.md
  docs/transform/modernize-scanner.md
Labels: pr:ready-to-merge

#5923 Add note about manual invocation only from default environment
  docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
Labels: pr:do-not-merge

#5932 Updated cmdlet to Register-SPOHubSite
  docs/features/hub-site/create-hub-site-with-powershell.md
Labels: pr:in-review

#5944 Corrected spelling
  docs/declarative-customization/list-form-conditional-show-hide.md
Labels: pr:in-review

#5945 Fixed missing space between words
  docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
Labels: pr:in-review

#5950 Add "which baseline packages" question to extension projects
  docs/spfx/extensions/get-started/build-a-hello-world-extension.md
  docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
  docs/spfx/extensions/get-started/building-simple-field-customizer.md
Labels: pr:in-review

#5958 Update list-form-conditional-show-hide.md
  docs/declarative-customization/list-form-conditional-show-hide.md
Labels: pr:in-review

#5961 Add troubleshooting tip for use with Azure Functions v3
  docs/sp-add-ins/using-csom-for-dotnet-standard.md
Labels: pr:ready-to-merge
