Repository SharePoint/sp-dev-docs, pull requests merged in 2020-07, with the labels that each got.

#5974 Update how-to-provide-add-in-app-only-tenant-administrative-permissio…
  docs/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online.md
Labels: pr:ready-to-merge

#5946 Restructures and expands 'Publish to SPFx marketplace' docs
  docs/spfx/publish-to-marketplace-after-publishing.md
  docs/spfx/publish-to-marketplace-checklist.md
  docs/spfx/publish-to-marketplace-faq.md
  docs/spfx/publish-to-marketplace-overview.md
  docs/spfx/publish-to-marketplace.md
  docs/spfx/toolchain/sharepoint-framework-toolchain.md
  docs/toc.yml
Labels: pr:ready-to-merge

#5992 Remove version links on "Set up your SharePoint Framework development environment"
  docs/spfx/set-up-your-development-environment.md
Labels: pr:in-review

#5994 Adds information about fullPageAppIconImageUrl
  docs/images/webparticon-fullpageappicon.png
  docs/images/webparticon-toolbox.png
  docs/spfx/web-parts/basics/configure-web-part-icon.md
Labels: pr:ready-to-merge

#5984 Update modern-experience-site-classification.md
  docs/solution-guidance/modern-experience-site-classification.md
Labels: pr:do-not-merge

#5991 Updated "PnP Provisioning Tenant Templates" page - "Create the Azure Function" section
  docs/declarative-customization/images/pnpprovisioning-experimental-features.png
  docs/declarative-customization/images/pnpprovisioning-runtime-settings.png
  docs/declarative-customization/images/pnpprovisioning-switch-classic-experience.png
  docs/declarative-customization/site-design-pnp-provisioning.md
Labels: pr:ready-to-merge

#5998 Update SPFx docs to refresh roadmap & add release notes
  docs/spfx/release-0.0.0.md.template
  docs/spfx/release-1.0.0.md
  docs/spfx/release-1.1.md
  docs/spfx/release-1.10.0.md
  docs/spfx/release-1.3.md
  docs/spfx/release-1.4.1.md
  docs/spfx/release-1.4.md
  docs/spfx/release-1.5.1.md
  docs/spfx/release-1.5.md
  docs/spfx/release-1.6.md
  docs/spfx/release-1.7.1.md
  docs/spfx/release-1.7.md
  docs/spfx/release-1.8.0.md
  docs/spfx/release-1.8.1.md
  docs/spfx/release-1.8.2.md
  docs/spfx/release-1.9.1.md
  docs/spfx/roadmap.md
  docs/toc.yml
Labels: pr:ready-to-merge

#6003 Update Use-remote-event-receivers-in-SharePoint.md
  docs/solution-guidance/Use-remote-event-receivers-in-SharePoint.md
Labels: pr:ready-to-merge

#6019 Fixed some minor typos
  docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md
Labels: pr:ready-to-merge

#6023 Added list of specific functional gaps
  docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md
Labels: pr:do-not-merge

#6050 Update SPFx release notes v1.11
  docs/spfx/release-1.11.0.md
  docs/toc.yml
Labels: pr:ready-to-merge

#6038 Update Typo in modernization scanner docs
  docs/transform/modernize-scanner.md
Labels: pr:ready-to-merge

#6041 Updating command line parameter -r
  docs/transform/modernize-scanner.md
Labels: pr:ready-to-merge

#6042 Fixing several textual errors in dynamic-data.md
  docs/spfx/dynamic-data.md
Labels: pr:ready-to-merge

#6048 Update team-based-development-on-sharepoint-framework.md
  docs/spfx/team-based-development-on-sharepoint-framework.md
Labels: pr:ready-to-merge

#6051 Correct simple grammar mistake
  docs/spfx/publish-to-marketplace-checklist.md
Labels: pr:ready-to-merge

#6052 Update migrate-from-classic-workflows-to-power-automate-flows.md
  docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md
Labels: pr:ready-to-merge

#6062 Update sharepoint-framework-toolchain.md
  docs/spfx/toolchain/sharepoint-framework-toolchain.md
Labels: pr:ready-to-merge

#6063 Update scaffolding-projects-using-yeoman-sharepoint-generator.md
  docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md
Labels: pr:ready-to-merge

#6064 Updated web part name
  docs/spfx/web-parts/get-started/add-jqueryui-accordion-to-web-part.md
Labels: pr:ready-to-merge

#6084 migrate-angular-1-x-applications-to-sharepoint-framework.md: fix broken links
  docs/spfx/web-parts/guidance/migrate-angular-1-x-applications-to-sharepoint-framework.md
Labels: pr:ready-to-merge

#6085 Fixed typos/grammar
  docs/spfx/office-addins-create.md
Labels: pr:ready-to-merge

#6069 Update compatibility.md
  docs/spfx/compatibility.md
Labels: pr:ready-to-merge

#6094 Update export-amr-api.md
  docs/apis/export-amr-api.md
Labels: pr:ready-to-merge

#6095 Fix url for spfx preview docs
  includes/snippets/developer-preview-notice.md
Labels: pr:ready-to-merge

#6103 Grammer correction - SPFX setting up environment.
  docs/spfx/set-up-your-development-environment.md
Labels: pr:ready-to-merge

#6108 $ missing in JSON schema
  docs/declarative-customization/view-formatting.md
Labels: pr:ready-to-merge

#6112 Update authorize-provider-hosted-add-in-users-at-run-time-by-using-oa…
  docs/solution-guidance/authorize-provider-hosted-add-in-users-at-run-time-by-using-oauth.md
Labels: pr:ready-to-merge

#6128 Fix doc typo
  docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
Labels: pr:ready-to-merge

#6120 Update JSON snippets in examples
  docs/spfx/dynamic-data.md
Labels: pr:ready-to-merge

#6124 fix link to tutorial in environment setup
  docs/spfx/set-up-your-development-environment.md
Labels: pr:do-not-merge
