Repository SharePoint/sp-dev-docs, pull requests merged in 2020-09, with the labels that each got.

#6224 Updated links to cli-microsoft365
  docs/declarative-customization/site-design-o365cli.md
Labels: pr:do-not-merge

#6229 Rename & update links for "Office 365 CLI" > "CLI for Microsoft 365"
  docs/apis/alm-api-for-spfx-add-ins.md
  docs/community/community.md
  docs/community/open-source-projects.md
  docs/declarative-customization/site-design-pnppowershell.md
  docs/declarative-customization/site-design-powershell.md
  docs/features/hub-site/hub-site-o365cli.md
  docs/features/hub-site/hub-site-overview.md
  docs/features/hub-site/hub-site-powershell.md
  docs/general-development/site-collection-app-catalog.md
  docs/index.yml
  docs/scenario-guidance/Custom-configurations.md
  docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
  docs/spfx/enable-Microsoft-365-content-delivery-network.md
  docs/spfx/publish-to-marketplace-checklist.md
  docs/spfx/release-0.0.0.md.template
  docs/spfx/release-1.0.0.md
  docs/spfx/release-1.1.md
  docs/spfx/release-1.10.0.md
  docs/spfx/release-1.11.0.md
  docs/spfx/release-1.3.md
  docs/spfx/release-1.4.1.md
  docs/spfx/release-1.4.md
  docs/spfx/release-1.5.1.md
  docs/spfx/release-1.5.md
  docs/spfx/release-1.6.md
  docs/spfx/release-1.7.1.md
  docs/spfx/release-1.7.md
  docs/spfx/release-1.8.0.md
  docs/spfx/release-1.8.1.md
  docs/spfx/release-1.8.2.md
  docs/spfx/release-1.9.1.md
  docs/spfx/tenant-properties.md
  docs/spfx/tenant-scoped-deployment.md
  docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
  docs/spfx/use-aadhttpclient.md
  docs/spfx/web-parts/single-part-app-pages.md
  docs/toc.yml
  includes/snippets/open-source/pnp-o365cli.md
Labels: area:docs, pr:ready-to-merge

#6226 Fixed invalid UserGroup.xml
  docs/apis/migration-api-shared.md
Labels: pr:ready-to-merge

#6239 CLI for Microsoft 365 Updates
  docs/apis/alm-api-for-spfx-add-ins.md
  docs/community/open-source-projects.md
  docs/general-development/site-collection-app-catalog.md
  docs/solution-guidance/modern-experience-customizations-provisioning-sites.md
  docs/spfx/enable-Microsoft-365-content-delivery-network.md
  docs/spfx/tenant-properties.md
  docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md
  docs/spfx/toolchain/implement-ci-cd-with-azure-pipelines.md
  docs/spfx/web-parts/single-part-app-pages.md
Labels: pr:ready-to-merge

#6266 Update site-collection-app-catalog.md
  docs/general-development/site-collection-app-catalog.md
Labels: Needs: Author Feedback, pr:do-not-merge

#6284 Update dynamic-loading.md
  docs/spfx/dynamic-loading.md
Labels: pr:ready-to-merge

#6311 Removing PnP PowerShell supportability notice
  docs/declarative-customization/site-design-powershell.md
Labels: pr:do-not-merge
