Repository SharePoint/sp-dev-docs, pull requests merged in 2021-03, with the labels that each got.

#6765 Updated cmdlets with the new names
  docs/solution-guidance/Introducing-the-PnP-Provisioning-Engine.md
Labels: pr:ready-to-merge

#6781 Minor typo fixes
  docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
Labels: pr:do-not-merge, pr:in-review

#6758 Added GCC High clarification.
  docs/spfx/set-up-your-developer-tenant.md
Labels: Needs: Author Feedback, pr:do-not-merge

#6795 Update modernize-connect-to-office365-group-permissions.md
  docs/transform/modernize-connect-to-office365-group-permissions.md
Labels: pr:ready-to-merge

#6805 Update modernize-connect-to-office365-group-permissions.md
  docs/transform/modernize-connect-to-office365-group-permissions.md
Labels: pr:ready-to-merge

#6784 Update site-design-pnppowershell.md
  docs/declarative-customization/site-design-pnppowershell.md
Labels: pr:ready-to-merge

#6796 spfx v1.12 release updates
  .openpublishing.redirection.json
  docs/images/sp-teams-admin-allow-side-loading.png
  docs/images/sp-teams-admin-extend-apps.png
  docs/images/sp-teams-admin-select-teams.png
  docs/images/sp-teams-move-to-admin.png
  docs/spfx/build-for-teams-considerations.md
  docs/spfx/build-for-teams-expose-webparts-teams.md
  docs/spfx/deployment-spfx-teams-solutions.md
  docs/spfx/integrate-with-teams-introduction.md
  docs/spfx/release-1.12.0.md
  docs/spfx/set-up-your-development-environment.md
  docs/spfx/web-parts/basics/determine-web-part-width.md
  docs/spfx/web-parts/guidance/creating-team-manifest-manually-for-webpart.md
  docs/toc.yml
Labels: pr:ready-to-merge

#6810 Update migration-api-overview.md
  docs/apis/migration-api-overview.md
Labels: pr:ready-to-merge

#6811 Update Modernization.PageTransformation link
  docs/transform/modernize-userinterface-site-pages-dotnet.md
Labels: pr:ready-to-merge

#6819 Update "Overwhelming" section with sync client ca
  docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Labels: pr:ready-to-merge

#6828 Corrected code snippet
  docs/general-development/managed-metadata-and-navigation-in-sharepoint.md
Labels: pr:ready-to-merge

#6849 clarify confusing grammer
  docs/sp-add-ins/context-token-oauth-flow-for-sharepoint-add-ins.md
Labels: pr:in-review

#6829 Azure function script example fix
  docs/declarative-customization/site-design-pnp-provisioning.md
Labels: pr:ready-to-merge

#6851 update spfx roadmap (post spfx v1.12
  docs/spfx/roadmap.md
Labels: pr:ready-to-merge

#6859 Update determine-web-part-width.md
  docs/spfx/web-parts/basics/determine-web-part-width.md
Labels: pr:ready-to-merge

#6860 Update semantic_slots.md
  docs/design/semantic_slots.md
Labels: pr:ready-to-merge

#6869 Update site-creation-rest.md
  docs/apis/site-creation-rest.md
Labels: pr:ready-to-merge

#6871 Change link to MSTeams deployment options
  docs/spfx/web-parts/get-started/using-web-part-as-ms-teams-tab.md
Labels: pr:ready-to-merge

#6872 Revert guidance to focus on SPFx v1.11
  docs/spfx/release-1.12.0.md
  docs/spfx/set-up-your-development-environment.md
  docs/toc.yml
Labels: pr:ready-to-merge
