Repository SharePoint/sp-dev-docs, pull requests merged in 2021-04, with the labels that each got.

#6884 Update site-design-rest-api.md
  docs/declarative-customization/site-design-rest-api.md
Labels: pr:ready-to-merge

#6887 Update configuring-the-pnp-provisioning-engine.md
  docs/solution-guidance/configuring-the-pnp-provisioning-engine.md
Labels: pr:in-review

#6911 Spfx v1.12.1 release
  docs/spfx/developer-preview-beta-features.md
  docs/spfx/release-1.12.1.md
  docs/toc.yml
  includes/snippets/spfx-release-candidate.md
Labels: pr:ready-to-merge

#6594 Fixed typos and improved formatting
  docs/declarative-customization/list-form-conditional-show-hide.md
Labels: pr:do-not-merge

#6926 Docs update for 1.12.1 & SPFx dev preview installs
  docs/spfx/developer-preview-beta-features.md
  docs/spfx/release-1.12.1.md
  docs/spfx/web-parts/get-started/deploy-web-part-to-cdn.md
Labels: pr:ready-to-merge

#6921 Added a code sample for lookup columns
  docs/declarative-customization/list-form-conditional-show-hide.md
Labels: pr:ready-to-merge

#6922 Update security-apponly-azureacs.md
  docs/solution-guidance/security-apponly-azureacs.md
Labels: pr:ready-to-merge

#6939 Converted issue templates to issue forms
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.yml
Labels: pr:ready-to-merge

#6936 Updated Links
  docs/solution-guidance/query-sharepoint-change-log-with-changequery-and-changeToken.md
Labels: pr:ready-to-merge

#6948 Updated "Unsupported column types"
  docs/declarative-customization/list-form-conditional-show-hide.md
Labels: pr:ready-to-merge

#6949 Removed "debugMode" attribute from sample JSON
  docs/declarative-customization/list-form-configuration.md
Labels: pr:ready-to-merge

#6956 SPFx v1.12.1 Release Notes & Docs on SPFx as Teams meetings apps
  docs/images/build-for-teams/build-for-pre-post-meeting-exp.png
  docs/images/build-for-teams/build-for-teams-meeting-app-add-app.png
  docs/spfx/build-for-teams-meeting-app.md
  docs/spfx/release-1.12.1.md
  docs/spfx/subscribe-to-list-notifications.md
  docs/toc.yml
Labels: pr:ready-to-merge

#6961 Update SPFx setup doc
  docs/spfx/set-up-your-development-environment.md
Labels: pr:ready-to-merge
