Repository SharePoint/sp-dev-docs, pull requests merged in 2021-07, with the labels that each got.

#7141 Update how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
  docs/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online.md
Labels: pr:ready-to-merge

#7153 Updated "Get started creating site designs and site scripts"
  docs/declarative-customization/get-started-create-site-design.md
Labels: pr:ready-to-merge

#7156 Typo Fix
  docs/transform/modernize-userinterface-site-pages-powershell.md
Labels: pr:ready-to-merge

#7064 FAQ converted into yml
  docs/general-development/excel-services-overview.md
  docs/general-development/excel-services-user-defined-functions.md
  docs/general-development/frequently-asked-questions-about-excel-services-udfs.md
  docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml
  docs/general-development/how-to-access-an-external-data-source-from-a-udf.md
  docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md
  docs/general-development/how-to-enable-udfs.md
  docs/general-development/how-to-restrict-udf-code-access-security-permissions.md
  docs/general-development/understanding-excel-services-udfs.md
  docs/spfx/known-issues-and-common-questions.md
  docs/spfx/known-issues-and-common-questions.yml
  docs/spfx/publish-to-marketplace-faq.md
  docs/spfx/publish-to-marketplace-faq.yml
  docs/spfx/publish-to-marketplace-overview.md
  docs/spfx/release-1.11.0.md
  docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
  docs/toc.yml
  docs/transform/modernize-scanner-faq.md
  docs/transform/modernize-scanner-faq.yml
Labels: pr:do-not-merge

#7181 Update event-receiver-and-list-event-receiver-sharepoint-add-in.md
  docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md
Labels: pr:ready-to-merge

#7186 Fix merge conflicts with existing PR
  docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md
Labels: pr:in-review

#7187 add caution note about unsupported upload of multiple files
  docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md
Labels: pr:in-review

#7189 update to make docs less "point-in-time"
  docs/spfx/toolchain/scaffolding-projects-using-yeoman-sharepoint-generator.md
Labels: pr:in-review

#7188 fix incorrect path to teams package
  docs/spfx/deployment-spfx-teams-solutions.md
Labels: pr:in-review

#7194 new tutorials
  docs/images/viva-extensibility/lab1-basic-ace.png
  docs/images/viva-extensibility/lab1-default.png
  docs/images/viva-extensibility/lab1-hw-ace.png
  docs/images/viva-extensibility/lab1-hw-ql.png
  docs/images/viva-extensibility/lab1-image-ace.png
  docs/images/viva-extensibility/lab1-large.png
  docs/images/viva-extensibility/lab1-new-ql.png
  docs/images/viva-extensibility/lab1-preview.png
  docs/images/viva-extensibility/lab1-primary-ace.png
  docs/images/viva-extensibility/lab1-size.png
  docs/images/viva-extensibility/lab1-static-ace.png
  docs/images/viva-extensibility/lab1-toolbox.png
  docs/images/viva-extensibility/lab2-ace-1.png
  docs/images/viva-extensibility/lab2-ace-2.png
  docs/images/viva-extensibility/lab2-ace-3.png
  docs/images/viva-extensibility/lab2-ace-4.png
  docs/images/viva-extensibility/lab2-ace-5.png
  docs/images/viva-extensibility/lab2-ace-6.png
  docs/images/viva-extensibility/lab2-empty-list.png
  docs/images/viva-extensibility/lab2-list-id.png
  docs/images/viva-extensibility/lab2-list-settings.png
  docs/images/viva-extensibility/lab3-ace-1.png
  docs/images/viva-extensibility/lab3-detailed.png
  docs/images/viva-extensibility/lab4-add.png
  docs/images/viva-extensibility/lab4-apps.png
  docs/images/viva-extensibility/lab4-catalog.png
  docs/images/viva-extensibility/lab4-confirm.png
  docs/images/viva-extensibility/lab4-deploy.png
  docs/images/viva-extensibility/lab4-new.png
  docs/images/viva-extensibility/lab4-sync.png
  docs/images/viva-extensibility/lab4-url.png
  docs/spfx/release-1.13.md
  docs/spfx/viva/get-started/adaptive-card-extensions-and-teams.md
  docs/spfx/viva/get-started/advanced-card-view-functionality.md
  docs/spfx/viva/get-started/advanced-quick-view-functionality.md
  docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md
  docs/spfx/viva/overview-viva-connections.md
  docs/toc.yml
  includes/snippets/spfx-release-beta.md
Labels: pr:in-review
