Repository SharePoint/sp-dev-docs, pull requests merged in 2021-02, with the labels that each got.

#6671 Update site-creation-rest.md
  docs/apis/site-creation-rest.md
Labels: pr:ready-to-merge

#6679 MSDocs build error fixes
  docs/general-development/develop-sharepoint-workflows-using-visual-studio.md
  docs/general-development/get-started-with-workflows-in-sharepoint.md
  docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md
Labels: pr:do-not-merge, pr:in-review

#6642 Updating Title to match the tutorial
  docs/business-apps/power-automate/get-started/create-your-first-flow.md
Labels: pr:ready-to-merge

#6676 Provides a link how to support % and # characters in files and folders.
  docs/sp-add-ins/working-with-folders-and-files-with-rest.md
Labels: pr:ready-to-merge

#6690 Updated code snippet
  docs/spfx/enable-Microsoft-365-content-delivery-network.md
Labels: pr:ready-to-merge

#6691 Modified the note at the start of the docs
  docs/declarative-customization/site-design-pnp-provisioning.md
Labels: pr:ready-to-merge

#6692 Migrate CSS change from wiki to docs
  docs/spfx/office-ui-fabric-integration.md
  docs/spfx/release-1.8.2.md
Labels: pr:ready-to-merge

#6674 Configuration file needs to be specified as .json file
  docs/solution-guidance/configuring-the-pnp-provisioning-engine.md
Labels: Needs: Author Feedback, pr:do-not-merge

#6713 clarified doc based on user question
  docs/spfx/extensions/basics/tenant-wide-deployment-extensions.md
Labels: area:docs, area:spfx-extensions, area:spfx-general, pr:ready-to-merge

#6714 Update migration-api-overview.md
  docs/apis/migration-api-overview.md
Labels: pr:ready-to-merge

#6711 Fix reference to old version of PnP PowerShell
  docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md
Labels: pr:in-review

#6718 update pnp-provisioning version
  docs/declarative-customization/site-design-pnp-provisioning.md
Labels: pr:do-not-merge, pr:in-review

#6726 Update column-formatting.md
  docs/declarative-customization/column-formatting.md
Labels: pr:ready-to-merge

#6732 Update column-formatting.md
  docs/declarative-customization/column-formatting.md
Labels: pr:ready-to-merge

#6733 Update site-design-pnppowershell.md
  docs/declarative-customization/site-design-pnppowershell.md
Labels: pr:ready-to-merge

#6739 Updated link
  docs/solution-guidance/modern-experience-customizations-customize-sites.md
Labels: pr:ready-to-merge

#6740 Updated link
  docs/solution-guidance/modern-experience-customizations-customize-pages.md
Labels: pr:ready-to-merge

#6741 Updated link
  docs/solution-guidance/modern-experience-customizations.md
Labels: pr:ready-to-merge

#6750 Updated description to match URL endpoint
  docs/sp-add-ins/get-to-know-the-sharepoint-rest-service.md
Labels: pr:ready-to-merge

#6667 Update migration-isv-guidance.md
  docs/apis/migration-isv-guidance.md
  docs/apis/migration-perm-guidance.md
  docs/apis/sp-migration-api-and-sensitivity-labels.md
  docs/toc.yml
Labels: pr:ready-to-merge

#6687 Update site-creation-rest.md
  docs/apis/site-creation-rest.md
Labels: pr:ready-to-merge

#6752 Updated module from SharePointPnPPowerShellOnline to PnP.PowerShell
  docs/solution-guidance/pnp-provisioning-engine-and-the-core-library.md
Labels: pr:ready-to-merge

#6756 Fixed typos
  docs/spfx/use-theme-colors-in-your-customizations.md
Labels: pr:ready-to-merge
