Repository SharePoint/sp-dev-docs, pull requests merged in 2021-01, with the labels that each got.

#6586 Custom formatter documentation update
  docs/declarative-customization/column-formatting.md
  docs/declarative-customization/view-formatting.md
  docs/images/sp-columnformatting-formatter-reference-1.png
  docs/images/sp-columnformatting-formatter-reference-2.png
  docs/images/sp-columnformatting-panel.png
  docs/images/sp-viewformatting-panel-listlayout.png
  docs/images/sp-viewformatting-panel-tileslayout.png
Labels: pr:do-not-merge, pr:in-review

#6583 Fixed broken links in article
  docs/solution-guidance/Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md
Labels: pr:ready-to-merge

#6589 Ms docs build error fixes
  docs/general-development/how-to-create-a-master-page-preview-file-in-sharepoint.md
  docs/general-development/how-to-deploy-a-custom-theme-in-sharepoint.md
  docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md
  docs/general-development/how-to-extend-the-geolocation-field-type-using-client-side-rendering.md
  docs/general-development/how-to-follow-people-by-using-the-javascript-object-model-in-sharepoint.md
  docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone-app-for-s.md
  docs/general-development/how-to-integrate-maps-with-windows-phone-apps-and-sharepoint-lists.md
  docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-net-client-object.md
  docs/general-development/how-to-locate-and-copy-microsoft-office-excel-webui-dll-and-microsoft-office-exc.md
  docs/general-development/how-to-programmatically-add-an-excel-web-access-web-part-to-a-page.md
  docs/general-development/how-to-save-to-the-server-to-prepare-for-programmatic-access.md
  docs/general-development/how-to-use-multiple-sharepoint-lists-in-a-windows-phone-app.md
  docs/general-development/how-to-use-the-content-enrichment-web-service-callout-for-sharepoint-server.md
  docs/general-development/step-2-creating-a-managed-code-udf.md
  docs/general-development/use-feature-upgrade-to-apply-new-sharepoint-master-pages-when-upgrading-fro.md
  docs/general-development/use-workflow-interop-for-sharepoint.md
  docs/general-development/working-with-web-services-in-sharepoint-workflows-using-visual-studio-2012.md
  docs/solution-guidance/Localize-UI-elements-sample-app-for-SharePoint.md
  docs/solution-guidance/app-only-elevated-privileges-sharepoint-add-in.md
  docs/solution-guidance/list-instance-sharepoint-add-in.md
  docs/sp-add-ins/add-a-custom-content-type-to-a-sharepoint-hosted-sharepoint-add-in.md
  docs/sp-add-ins/add-custom-columns-to-a-sharepoint-hosted-sharepoint-add-in.md
  docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md
  docs/sp-add-ins/explore-the-app-manifest-structure-and-the-package-of-a-sharepoint-add-in.md
  docs/sp-add-ins/host-webs-add-in-webs-and-sharepoint-components-in-sharepoint.md
  docs/sp-add-ins/localize-sharepoint-add-ins.md
  docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md
  docs/sp-add-ins/update-add-in-web-components-in-sharepoint.md
  docs/sp-add-ins/work-with-host-web-data-from-javascript-in-the-add-in-web.md
Labels: pr:ready-to-merge

#6593 Update migration-api-overview.md
  docs/apis/migration-api-overview.md
Labels: pr:ready-to-merge

#6606 Fixed typos and improved code formatting
  docs/declarative-customization/list-form-configuration.md
Labels: pr:ready-to-merge

#6607 fixed table content
  docs/schema/field-element-list.md
Labels: pr:ready-to-merge

#6614 Fixed broken link
  docs/general-development/advanced-scenarios-and-additional-samples.md
Labels: pr:ready-to-merge

#6615 Update modernize-connect-to-office365-group.md
  docs/transform/modernize-connect-to-office365-group.md
Labels: pr:ready-to-merge

#6628 update doc to remove broken link
  docs/spfx/web-parts/basics/add-an-external-library.md
Labels: pr:ready-to-merge

#6632 revert previous commit, replacing text with valid link
  docs/spfx/web-parts/basics/add-an-external-library.md
Labels: pr:in-review

#6646 Body format displayname should be lowercase
  docs/declarative-customization/list-form-configuration.md
Labels: pr:ready-to-merge

#6658 Event receiver doc fixup
  docs/solution-guidance/event-receiver-and-list-event-receiver-sharepoint-add-in.md
Labels: pr:do-not-merge, pr:in-review
