Repository SharePoint/sp-dev-docs, pull requests merged in 2021-06, with the labels that each got.

#7035 Update client-side-web-parts-maintenance-mode.md
  docs/general-development/client-side-web-parts-maintenance-mode.md
Labels: pr:in-review

#7038 Add note about no support for chunked upload in SharePoint Server
  docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
Labels: pr:in-review

#7040 Fix small typo
  docs/index.yml
Labels: pr:ready-to-merge

#7061 Updating link to property column formatting tool.
  docs/declarative-customization/view-formatting.md
Labels: pr:ready-to-merge

#7037 Update list permissions level for run-only flow users
  docs/business-apps/power-automate/guidance/manage-list-flows.md
Labels: pr:ready-to-merge

#7045 Adding the newest trigger
  docs/business-apps/power-automate/sharepoint-connector-actions-triggers.md
Labels: pr:ready-to-merge

#7067 Update development-experience-tenant-apponly-permissions-in-sharepoin…
  docs/solution-guidance/development-experience-tenant-apponly-permissions-in-sharepoint-online.md
Labels: pr:ready-to-merge

#7082 Update sharepoint-add-in-recipes.md
  docs/solution-guidance/sharepoint-add-in-recipes.md
Labels: pr:ready-to-merge

#7017 Update create-your-first-flow.md
  docs/business-apps/power-automate/get-started/create-your-first-flow.md
  docs/images/lists-integrate-power-automate-create-flow.png
Labels: pr:ready-to-merge

#7090 Updated link and code for CLI for Microsoft 365
  docs/spfx/web-parts/single-part-app-pages.md
Labels: pr:ready-to-merge

#7062 Adds information about using MGT in SPFx
  docs/spfx/use-microsoft-graph-toolkit.md
  docs/spfx/web-parts/get-started/build-web-part-microsoft-graph-toolkit.md
  docs/toc.yml
Labels: pr:do-not-merge

#7088 Corrected "Formatter Tool helper" hyperlink
  docs/declarative-customization/column-formatting.md
Labels: pr:ready-to-merge

#7094 Corrected typo 'ClientSiteComponentId'
  docs/spfx/extensions/get-started/building-simple-field-customizer.md
Labels: pr:in-review

#7097 Added a note regarding Workflow Item Templates
  docs/sp-add-ins/add-a-workflow-to-a-sharepoint-hosted-sharepoint-add-in.md
Labels: pr:ready-to-merge

#7107 Fix #7104
  docs/solution-guidance/multigeo-sites.md
Labels: pr:ready-to-merge

#7019 Update migration-api-overview.md
  docs/apis/migration-api-overview.md
Labels: Needs: Author Feedback, pr:do-not-merge

#7018 Update connect-to-other-services-in-your-flow.md
  docs/business-apps/power-automate/get-started/connect-to-other-services-in-your-flow.md
Labels: pr:do-not-merge

#7108 fix broken links
  docs/spfx/compatibility.md
Labels: pr:ready-to-merge

#7110 Update docs for SPFx & onprem deployments
  docs/spfx/set-up-your-development-environment.md
  docs/spfx/sharepoint-2016-support.md
  docs/spfx/sharepoint-2019-support.md
Labels: pr:ready-to-merge

#7111 add additional note to avoid confusion
  docs/spfx/web-parts/get-started/connect-to-sharepoint.md
Labels: pr:ready-to-merge

#7112 update hello world web part docs
  docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md
Labels: pr:ready-to-merge

#7113 correct statment on max cert expiry date
  docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md
Labels: pr:ready-to-merge

#7114 Add note about limitation with sp2016 & preconf entries
  docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
Labels: pr:in-review

#7115 [[WIP]] Fixup msdocs rules
  docs/general-development/how-to-make-custom-css-files-themable-in-sharepoint.md
  docs/general-development/how-to-resolve-errors-and-warnings-when-previewing-a-page-in-sharepoint.md
  docs/general-development/how-to-store-and-retrieve-sharepoint-list-items-on-a-windows-phone.md
  docs/scenario-guidance/Long-running-scheduled-operations.md
  docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md
  docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md
  docs/transform/modernize-blogs.md
Labels: pr:do-not-merge

#7119 Fix multiple MSDOCS build errors
  README.md
  docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md
  docs/community/community.md
  docs/features/embed-pages-to-teams.md
  docs/general-development/advanced-scenarios-and-additional-samples.md
  docs/general-development/code-samples-for-sharepoint.md
  docs/general-development/color-palettes-and-fonts-in-sharepoint.md
  docs/general-development/excel-services-in-sharepoint.md
  docs/general-development/how-to-create-a-master-page-preview-file-in-sharepoint.md
  docs/general-development/removing-excel-interactive-view-from-a-webpage.md
  docs/general-development/themes-overview-for-sharepoint.md
  docs/general-development/upgrade-custom-themes-and-css-to-sharepoint.md
  docs/general-development/workflow-initiation-and-configuration-properties.md
  docs/index.yml
  docs/solution-guidance/Sandbox-Solution-Transformation-Guidance-Feature-Receivers.md
  docs/solution-guidance/branding-sharepoint-sites-sharepoint-add-in.md
  docs/solution-guidance/custom-field-type-sharepoint-add-in.md
  docs/solution-guidance/delegate-controls-sharepoint-add-in.md
  docs/solution-guidance/document-id-provider-sharepoint-add-in.md
  docs/solution-guidance/feature-stapling-sharepoint-add-in.md
  docs/solution-guidance/how-to-provide-add-in-app-only-tenant-administrative-permissions-in-sharepoint-online.md
  docs/solution-guidance/information-management-policy-sharepoint-add-in.md
  docs/solution-guidance/javascript-patterns-and-performance.md
  docs/solution-guidance/list-definition-template-sharepoint-add-in.md
  docs/solution-guidance/localization-sharepoint-add-in.md
  docs/solution-guidance/master-pages-sharepoint-add-in.md
  docs/solution-guidance/mms-manipulation-sharepoint-add-in.md
  docs/solution-guidance/modern-experience-customizations-customize-pages.md
  docs/solution-guidance/modules-sharepoint-add-in.md
  docs/solution-guidance/performance-considerations-sharepoint-add-in.md
  docs/solution-guidance/portal-branding.md
  docs/solution-guidance/portal-information-architecture.md
  docs/solution-guidance/remote-timer-jobs-sharepoint-add-in.md
  docs/solution-guidance/search-configuration-sharepoint-add-in.md
  docs/solution-guidance/site-columns-and-content-types-sharepoint-add-in.md
  docs/solution-guidance/site-provisioning-sharepoint-add-in.md
  docs/solution-guidance/template-for-sharepoint-add-in.md.template
  docs/solution-guidance/user profile manipulation-sharepoint-add-in.md
  docs/solution-guidance/user-controls-and-web-controls-sharepoint-add-in.md
  docs/solution-guidance/web-part-sharepoint-add-in.md
  docs/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code.md
  docs/spfx/build-for-teams-meeting-app.md
  docs/spfx/extensions/get-started/build-a-hello-world-extension.md
  docs/spfx/extensions/get-started/building-simple-field-customizer.md
  docs/spfx/release-1.11.0.md
  docs/spfx/web-parts/guidance/simplify-adding-web-parts-with-preconfigured-entries.md
Labels: pr:ready-to-merge

#7126 Update set-up-your-development-environment.md
  docs/spfx/set-up-your-development-environment.md
Labels: pr:ready-to-merge

#7127 Updated column-formatting.md - Remove unnecessary double quotation marks.
  docs/declarative-customization/column-formatting.md
Labels: pr:ready-to-merge
