Repository SharePoint/sp-dev-docs, pull requests merged in 2022-10, with the labels that each got.

#8475 Update to sample Site Script code
  docs/declarative-customization/get-started-create-site-design.md
Labels: pr:ready-to-merge

#8459 Bulk Metadata Update - Replacing ms.topic values.
  docs/scenario-guidance/Development-models.md
  docs/scenario-guidance/Line-of-Business-integration.md
  docs/scenario-guidance/Responding-to-changes.md
  docs/scenario-guidance/Site-provisioning.md
  docs/scenario-guidance/Solutions-deployment.md
  docs/schema/propertyrules-element-propertyrulecollection-complextypesps15xsdsearchset2.md
  docs/solution-guidance/security-apponly-azureacs.md
  docs/solution-guidance/security-apponly-azuread.md
  docs/solution-guidance/security-apponly.md
  docs/solution-guidance/security-webapppolicies.md
Labels: pr:ready-to-merge

#8476 Corrected split operator syntax
  docs/declarative-customization/formatting-syntax-reference.md
Labels: pr:ready-to-merge

#8481 Update toc.yml
  docs/toc.yml
Labels: pr:ready-to-merge

#8505 correct broken & redirection links
  docs/general-development/debugging-sharepoint-server-workflows.md
  docs/general-development/how-to-create-custom-sharepoint-server-workflow-forms-with-visual-studio-20.md
  docs/general-development/how-to-create-sharepoint-workflows-using-visual-studio.md
  docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md
  docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md
  docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md
  docs/general-development/working-with-web-services-in-sharepoint-workflows-using-visual-studio-2012.md
  docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md
Labels: pr:ready-to-merge

#8503 Update sharepoint-site-theming-json-schema.md
  docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
Labels: pr:ready-to-merge

#8512 Update sharepoint-site-theming-overview.md
  docs/declarative-customization/site-theming/sharepoint-site-theming-overview.md
Labels: pr:ready-to-merge

#8422 Clarify & provide example of the validation return
  docs/apis/webhooks/lists/create-subscription.md
Labels: area:docs, Needs: Author Feedback, pr:ready-to-merge

#8511 Update syntex-model-rest-api.md
  docs/apis/syntex/syntex-model-rest-api.md
Labels: pr:ready-to-merge

#8521 Updated security-apponly-azureacs.md
  docs/solution-guidance/security-apponly-azureacs.md
Labels: pr:in-review
