Repository SharePoint/sp-dev-docs, pull requests merged in 2022-05, with the labels that each got.

#7965 Update migration-api-overview.md
  docs/apis/migration-api-overview.md
Labels: pr:ready-to-merge

#7966 Create migration-api-whats-new
  docs/apis/migration-api-whats-new
Labels: pr:in-review

#7986 Fix doc link & text reference
  docs/support-feedback.md
Labels: pr:ready-to-merge

#7930 update metadata from ms.prod to ms.service
  docs/docfx.json
Labels: pr:do-not-merge
