Repository SharePoint/sp-dev-docs, pull requests merged in 2023-08, with the labels that each got.

#9113 Dark Mode for Quickview in Viva Connections Mobile
  docs/images/viva-design/img_quickview_new_ios_theme.png
  docs/images/viva-design/img_quickview_tutorial_dark.png
  docs/images/viva-design/img_quickview_tutorial_light.png
  docs/images/viva-design/img_quickview_tutorial_light_and_dark.png
  docs/spfx/viva/design/designing-quick-view.md
  docs/spfx/viva/get-started/making-quickview-compatable-darkmode-mobile.md
Labels: pr:do-not-merge

#9087 Update multigeo-managedmetadata.md
  docs/solution-guidance/multigeo-managedmetadata.md
Labels: Needs: Author Feedback, pr:ready-to-merge

#9132 Changed on to one
  docs/solution-guidance/security-webapppolicies.md
Labels: pr:ready-to-merge

#9136 remove iframe tag
  docs/spfx/use-microsoft-graph-toolkit.md
Labels: pr:ready-to-merge

#9156 Update export-amr-api.md
  docs/apis/export-amr-api.md
Labels: pr:ready-to-merge

#9157 Main
  docs/apis/migration-api-whats-new.md
Labels: pr:ready-to-merge

#9154 Create export-amr-api-permission-guide
  docs/apis/export-amr-api-permission-guide.md
Labels: pr:ready-to-merge

#9155 Update toc.yml
  docs/toc.yml
Labels: pr:ready-to-merge

#9164 Michal ziemba patch 1
  docs/declarative-customization/site-design-pnp-provisioning.md
Labels: pr:ready-to-merge
