Repository SharePoint/sp-dev-docs, pull requests merged in 2023-04, with the labels that each got.

#8861 Update migration-perm-guidance.md
  docs/apis/migration-perm-guidance.md
Labels: pr:ready-to-merge

#8862 🐞 typos & markdown errors
  docs/spfx/sharepoint-2019-and-subscription-edition-support.md
Labels: pr:ready-to-merge

#8865 ♻️ improve readability with acrolinx
  docs/apis/migration-perm-guidance.md
Labels: pr:in-review

#8848 Update for the GA of Top Actions
  docs/spfx/web-parts/guidance/getting-started-with-top-actions.md
Labels: pr:do-not-merge

#8840 Add Addin API doc
  docs/apis/addin-management-apis.md
  docs/toc.yml
Labels: pr:ready-to-merge

#8868 Updates SPFx compatibility matrix with v1.17.0
  docs/spfx/compatibility.md
Labels: pr:ready-to-merge

#8872 update for img src tags
  docs/declarative-customization/formatting-syntax-reference.md
Labels: pr:ready-to-merge

#8882 Update use-sp-pnp-js-with-spfx-web-parts.md
  docs/spfx/web-parts/guidance/use-sp-pnp-js-with-spfx-web-parts.md
Labels: pr:ready-to-merge

#8885 Update migration-api-whats-new.md
  docs/apis/migration-api-whats-new.md
Labels: pr:ready-to-merge

#8894 🐞 fixup markdown & build errors flagged by msdocs
  docs/spfx/release-1.17.1.md
  docs/spfx/release-1.17.md
Labels: pr:ready-to-merge

#8910 SPFx version number updated from 1.16 to 1.17.1
  docs/spfx/set-up-your-development-environment.md
Labels: pr:ready-to-merge
