Repository SharePoint/sp-dev-docs, pull requests merged in 2024-08, with the labels that each got.

#9826 Update custom formatter docs[Image field]
  docs/declarative-customization/formatting-syntax-reference.md
Labels: pr:in-review

#9840 Add Learning Tutorial For Migrating ABS to SPE
  docs/embedded/images/app-registration-console-platform.png
  docs/embedded/tutorials/migrate-abs-to-spe.md
Labels: pr:ready-to-merge

#9851 ♻️ improve readaibility score
  docs/embedded/tutorials/migrate-abs-to-spe.md
Labels: pr:ready-to-merge

#9849 Updated Generator 'Info' For "SharePoint site theming: JSON schema"
  docs/declarative-customization/site-theming/sharepoint-site-theming-json-schema.md
Labels: pr:ready-to-merge

#9867 add mention of spfx envvar to set on dev env
  docs/spfx/set-up-your-development-environment.md
Labels: pr:ready-to-merge

#9863 Fixed "SharePoint Look Book" broken link
  docs/transform/modernize-userinterface-site-pages.md
Labels: pr:in-review

#9833 Billing update
  docs/embedded/concepts/admin-exp/billing/billing.md
  docs/embedded/concepts/admin-exp/billing/meters.md
  docs/embedded/concepts/admin-exp/consuming-tenant-admin/cta.md
  docs/embedded/images/DTCBilling1.png
  docs/embedded/images/DTCBilling2.png
Labels: pr:ready-to-merge

#9855 Add Migrate ABS 2 SPE to TOC
  docs/toc.yml
Labels: pr:ready-to-merge

#9858 Update spfx-sharepoint-online.md
  docs/spfx/spfx-sharepoint-online.md
Labels: pr:ready-to-merge

#9861 Added --global to yo@4.3.1 installation note
  docs/spfx/set-up-your-development-environment.md
Labels: pr:ready-to-merge

#9876 fix formatting typo
  docs/spfx/set-up-your-development-environment.md
Labels: pr:ready-to-merge

#9811 Update build-data-visualization-adaptive-card-extension.md
  docs/images/viva-extensibility/data-visualization/bar-chart.png
  docs/images/viva-extensibility/data-visualization/donut-chart.png
  docs/images/viva-extensibility/data-visualization/pie-chart.png
  docs/spfx/viva/get-started/build-data-visualization-adaptive-card-extension.md
Labels: pr:do-not-merge

#9878 Update build-for-teams-me-experience.md
  docs/spfx/build-for-teams-me-experience.md
Labels: pr:in-review

#9879 Update integrate-with-teams-introduction.md
  docs/spfx/integrate-with-teams-introduction.md
Labels: pr:in-review

#9887 Add ManageContent
  docs/embedded/concepts/app-concepts/auth.md
Labels: pr:ready-to-merge

#9892 [Custom formatter docs update]Unsupported types in column formatter references
  docs/declarative-customization/formatting-syntax-reference.md
Labels: pr:ready-to-merge

#9894 Content update/ace updates
  docs/images/viva-extensibility/ace-basic-html-quickview-01.png
  docs/images/viva-extensibility/ace-basic-html-quickview-02.png
  docs/images/viva-extensibility/data-visualization/ace-dataviz-allup.png
  docs/spfx/release-1.14.md
  docs/spfx/release-1.15.2.md
  docs/spfx/release-1.15.md
  docs/spfx/release-1.17.md
  docs/spfx/release-1.18.1.md
  docs/spfx/release-1.18.md
  docs/spfx/release-1.19.md
  docs/spfx/release-1.20.md
  docs/spfx/roadmap.md
  docs/spfx/viva/design/design-intro.md
  docs/spfx/viva/design/designing-card.md
  docs/spfx/viva/design/designing-quick-view.md
  docs/spfx/viva/design/quick-view-samples.md
  docs/spfx/viva/features/card-designer/card-designer-api-support.md
  docs/spfx/viva/features/focus-feature/FocusFeatureDocumentation.md
  docs/spfx/viva/features/focus-feature/FocusFeatureTutorial.md
  docs/spfx/viva/get-started/actions/media-upload/MediaUploadDocumentation.md
  docs/spfx/viva/get-started/actions/media-upload/MediaUploadPropertyPane.md
  docs/spfx/viva/get-started/actions/media-upload/MediaUploadTutorial.md
  docs/spfx/viva/get-started/advanced-card-view-functionality.md
  docs/spfx/viva/get-started/advanced-quick-view-functionality.md
  docs/spfx/viva/get-started/build-data-visualization-adaptive-card-extension.md
  docs/spfx/viva/get-started/build-first-sharepoint-adaptive-card-extension.md
  docs/spfx/viva/get-started/build-html-quickview-adaptive-card-extension.md
  docs/spfx/viva/get-started/build-people-search-adaptive-card-extension.md
  docs/spfx/viva/get-started/fluent-icons-limitations.md
  docs/spfx/viva/get-started/making-quickview-compatable-darkmode-mobile.md
  docs/spfx/viva/get-started/migrate-to-spfx-1-18.md
  docs/spfx/viva/overview-viva-connections.md
  docs/toc.yml
Labels: pr:ready-to-merge
