Repository SharePoint/sp-dev-docs, pull requests merged in 2024-05, with the labels that each got.

#9649 Fix formatting doc for executeFlow and embed actions
  docs/declarative-customization/formatting-syntax-reference.md
Labels: Needs: Author Feedback, pr:ready-to-merge

#9651 Prepare for domain isolated web part retirement
  docs/images/discoverdomainisolatedwebpartusage.png
  docs/spfx/web-parts/isolated-web-parts-retirement.md
  docs/spfx/web-parts/isolated-web-parts.md
  docs/toc.yml
Labels: Needs: Author Feedback, pr:do-not-merge

#9676 Clarification of permission requirement on containers.
  docs/apis/migration-api-reference.md
  docs/apis/migration-azure.md
Labels: pr:ready-to-merge

#9683 Removing import { override } from '@microsoft/decorators';
  docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md
Labels: pr:ready-to-merge

#9688 Update view-commandbar-formatting.md
  docs/declarative-customization/view-commandbar-formatting.md
Labels: pr:ready-to-merge

#9690 Fixed typo in the menu
  docs/toc.yml
Labels: pr:ready-to-merge

#9691 ♻️ fix typo & markdown formatting
  docs/spfx/web-parts/isolated-web-parts-retirement.md
  docs/spfx/web-parts/isolated-web-parts.md
  docs/toc.yml
Labels: pr:ready-to-merge

#9703 🐞 fix typo
  docs/spfx/release-1.19.md
Labels: pr:ready-to-merge

#9704 Fixup in set-up-your-development-environment. Closes: #9684
  docs/spfx/set-up-your-development-environment.md
Labels: pr:ready-to-merge

#9713 address markdown & acrolinx findings
  docs/embedded/concepts/admin-exp/adminrole.md
  docs/embedded/concepts/admin-exp/billing/billing.md
  docs/embedded/concepts/admin-exp/billing/billingmanagement.md
  docs/embedded/concepts/admin-exp/billing/meters.md
  docs/embedded/concepts/admin-exp/consuming-tenant-admin/cta.md
  docs/embedded/concepts/admin-exp/consuming-tenant-admin/ctaUX.md
  docs/embedded/concepts/admin-exp/consuming-tenant-admin/ctapowershell.md
  docs/embedded/concepts/admin-exp/developer-admin/dev-admin.md
  docs/embedded/concepts/app-concepts/app-architecture.md
  docs/embedded/concepts/app-concepts/auth.md
  docs/embedded/concepts/app-concepts/containertypes.md
  docs/embedded/concepts/app-concepts/limits-calling.md
  docs/embedded/concepts/app-concepts/register-api-documentation.md
  docs/embedded/concepts/app-concepts/sharing-and-perm.md
  docs/embedded/concepts/content-experiences/office-experience.md
  docs/embedded/concepts/content-experiences/search-content.md
  docs/embedded/concepts/content-experiences/user-experiences-overview.md
  docs/embedded/concepts/fluid.md
  docs/embedded/getting-started/spembedded-for-vscode.md
  docs/embedded/overview.md
  docs/embedded/scenarios-and-use-cases.md
  docs/embedded/tutorials/doc-processing-acs.md
  docs/embedded/tutorials/launch-experience.md
  docs/embedded/tutorials/using-file-preview.md
  docs/embedded/tutorials/using-webhooks.md
Labels: pr:ready-to-merge

#9714 fixup spe ga redirects
  .openpublishing.redirection.json
Labels: pr:ready-to-merge

#9717 [SPE] Remove references to Sites.FullControl.All from SPE auth docs
  docs/embedded/concepts/app-concepts/auth.md
Labels: pr:ready-to-merge
