Repository SharePoint/sp-dev-docs, pull requests merged in 2025-05, with the labels that each got.

#10218 Update meters.md
  docs/embedded/administration/billing/meters.md
Labels: pr:ready-to-merge

#10216 Added automated issue closing for archived.
  .github/label-actions.yml
  .github/workflows/label-actions.yml
Labels: pr:in-review

#10209 debug manifests.js file path reference updated
  docs/spfx/debug-in-vscode.md
  docs/spfx/debug-modern-pages.md
  docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md
  docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md
  docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md
Labels: pr:in-review

#10222 🆕 New doc for SPO support for CSP & impacts on SPFx solutions
  docs/images/content-securty-policy-trusted-script-sources/add-app-with-tss.png
  docs/images/content-securty-policy-trusted-script-sources/add-script-source.png
  docs/images/content-securty-policy-trusted-script-sources/browser-console.png
  docs/images/content-securty-policy-trusted-script-sources/purview-audit-record.png
  docs/images/content-securty-policy-trusted-script-sources/purview-results.png
  docs/images/content-securty-policy-trusted-script-sources/purview-search.png
  docs/images/content-securty-policy-trusted-script-sources/spac-tss-nav.png
  docs/images/content-securty-policy-trusted-script-sources/spac-tss-page.png
  docs/spfx/content-securty-policy-trusted-script-sources.md
  docs/toc.yml
Labels: pr:in-review

#10223 Update view-commandbar-formatting.md
  docs/declarative-customization/view-commandbar-formatting.md
Labels: pr:ready-to-merge

#10240 Update SDK to version v1.0.9
  docs/embedded/development/tutorials/spe-da-vscode.md
Labels: pr:ready-to-merge

#10260 Clarify instructions to grant admin consent for SPE application
  docs/embedded/development/auth.md
Labels: pr:ready-to-merge

#10249 Update SPE agent spe-da.md
  docs/embedded/development/declarative-agent/spe-da.md
  docs/embedded/development/declarative-agent/spe-da2.md
Labels: pr:do-not-merge, Needs: Author complete CLA

#10262 Clarify exceptional access pattern for SPE requiring user licenses
  docs/embedded/development/auth.md
Labels: pr:ready-to-merge

#10266 Minor Update view-commandbar-formatting.md
  docs/declarative-customization/view-commandbar-formatting.md
Labels: pr:ready-to-merge

#10272 Update view-commandbar-formatting.md
  docs/declarative-customization/view-commandbar-formatting.md
Labels: pr:ready-to-merge

#10277 SPE: Update Container Type limit per tenant
  docs/embedded/development/limits-calling.md
Labels: pr:ready-to-merge

#10278 Fix TOC entries for SharePoint Embedded agent
  docs/toc.yml
Labels: pr:ready-to-merge

#10281 Update overview.md
  docs/embedded/overview.md
Labels: pr:ready-to-merge
